[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<iot_demo.cpp> +<ultrasonic_motor.cpp>
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
