const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'), ctx=canvas.getContext('2d');
const state={room:0,score:0,sanity:100,found:new Set(),journal:[],started:0,paused:false,keys:{},player:{x:3.5,y:6.5,a:-Math.PI/2},settings:{tone:2,hair:2,coat:1,difficulty:'detective',name:'MARA VOSS'}};
const maps=[
 {name:'THE ARCHIVE',objective:'Find what does not belong.',map:['1111111111','1000000001','1020000201','1001100001','1001100301','1000000001','1040000201','1111101111','1000000001','1111111111'],items:[
  {x:2.5,y:2.5,type:'file',title:'The Misdated Report',text:'A report dated three days before the victim vanished. Its page numbers hide a sequence.',visual:'2 · 3 · 5 · 8 · 13 · ?',answers:['18','20','21','26'],correct:2,clue:'The report was prepared in advance.'},
  {x:7.5,y:2.5,type:'clock',title:'The Silent Clock',text:'The clock stopped at 11:47. A note reads: “Mirror the hour, subtract the dead.” What is 74 − 11?',visual:'11:47  →  74 − 11',answers:['53','61','63','67'],correct:2,clue:'The stopped time yields the lock code: 63.'},
  {x:7.5,y:6.5,type:'photo',title:'The Impossible Photograph',text:'Four people face the camera. Ada stands left of Bell. Cole is not beside Ada. Dain stands far right. Who must stand second?',visual:'[ ? ]  [ ? ]  [ ? ]  [ DAIN ]',answers:['Ada','Bell','Cole','Dain'],correct:1,clue:'Bell occupied the blind spot in the photograph.'}],exit:{x:5.5,y:7.5}},
 {name:'THE OBSERVATION WARD',objective:'Reconstruct the final hour.',map:['1111111111','1000000001','1020110201','1000000001','1011001101','1000000001','1030000201','1110111111','1000000001','1111111111'],items:[
  {x:2.5,y:2.5,type:'tape',title:'Reversed Testimony',text:'The witness says: “I arrived after Nora, but before Eli. Eli arrived before Sol.” Who arrived first?',visual:'NORA · WITNESS · ELI · SOL',answers:['The witness','Nora','Eli','Sol'],correct:1,clue:'Nora entered the ward first.'},
  {x:7.5,y:2.5,type:'chart',title:'Pulse Record',text:'The monitor repeats a rule: 3→10, 5→26, 7→50. Complete 9→?',visual:'n  →  n² + 1',answers:['72','80','82','91'],correct:2,clue:'The pulse machine was deliberately set to 82.'},
  {x:7.5,y:6.5,type:'vial',title:'Three Vials',text:'Red is not poison. Blue lies whenever Green tells truth. Green says “Blue is poison.” If exactly one statement is true, which vial is poison?',visual:'RED   BLUE   GREEN',answers:['Red','Blue','Green','None'],correct:2,clue:'Green contained the sedative.'}],exit:{x:4.5,y:7.5}},
 {name:'THE BLACK STUDY',objective:'Name the architect of the crime.',map:['1111111111','1000000001','1020100201','1000000001','1011110101','1000000001','1030000201','1111011111','1000000001','1111111111'],items:[
  {x:2.5,y:2.5,type:'cipher',title:'The Architect’s Cipher',text:'Using A=1, B=2… decode 22-15-19-19. The name has followed you since the beginning.',visual:'22 · 15 · 19 · 19',answers:['VOSS','WARD','BELL','NOIR'],correct:0,clue:'VOSS — your own surname — is embedded in the cipher.'},
  {x:7.5,y:2.5,type:'letter',title:'A Letter to Yourself',text:'“Every room is a memory. Every clue is a correction.” Which earlier clue proves planning before the disappearance?',visual:'CAUSE  ←  ?  ←  EFFECT',answers:['The pulse','The photograph','The report','The green vial'],correct:2,clue:'The pre-dated report establishes premeditation.'},
  {x:7.5,y:6.5,type:'mirror',title:'The Final Reflection',text:'You have accused Bell, Nora, and the ward. But who had access to every room, every clue, and every memory?',visual:'THE DOOR OPENS INWARD',answers:['Bell','Nora','The caretaker','Mara Voss'],correct:3,clue:'You built the rooms to hide your own confession.'}],exit:{x:5.5,y:7.5}}
];
const diff={rookie:{drain:.15,mistakes:4},detective:{drain:.25,mistakes:3},inspector:{drain:.4,mistakes:2},nightmare:{drain:.7,mistakes:1}};

function buildSwatches(){
 const groups=[['tones',['#efc09b','#a97559','#714735']],['hairs',['#171412','#5d3c27','#c7ae86']],['coats',['#38443c','#3c3443','#56432f']]];
 groups.forEach(([id,colors])=>{const root=$('#'+id);colors.forEach((c,i)=>{const b=document.createElement('button');b.style.setProperty('--swatch',c);b.className=i+1===state.settings[id==='tones'?'tone':id==='hairs'?'hair':'coat']?'active':'';b.onclick=()=>{state.settings[id==='tones'?'tone':id==='hairs'?'hair':'coat']=i+1;[...root.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');updateAvatar()};root.append(b)})})
}
function updateAvatar(){const a=$('#avatar');a.className=`avatar tone-${state.settings.tone}`;a.querySelector('.avatar-hair').className=`avatar-hair hair-${state.settings.hair}`;a.querySelector('.avatar-coat').className=`avatar-coat coat-${state.settings.coat}`}
buildSwatches();

function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)} addEventListener('resize',resize);resize();
function current(){return maps[state.room%maps.length]}
let ambience;
function startAmbience(){
 if(ambience){ambience.resume();return}
 const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
 ambience=new AudioContext();const master=ambience.createGain();master.gain.value=.12;master.connect(ambience.destination);
 const seconds=3,buffer=ambience.createBuffer(1,ambience.sampleRate*seconds,ambience.sampleRate),data=buffer.getChannelData(0);
 let last=0;for(let i=0;i<data.length;i++){const white=Math.random()*2-1;last=.985*last+.015*white;data[i]=last*2.2}
 const wind=ambience.createBufferSource(),windFilter=ambience.createBiquadFilter(),windGain=ambience.createGain();wind.buffer=buffer;wind.loop=true;windFilter.type='lowpass';windFilter.frequency.value=480;windGain.gain.value=.42;wind.connect(windFilter).connect(windGain).connect(master);wind.start();
 [43,57].forEach((frequency,index)=>{const drone=ambience.createOscillator(),gain=ambience.createGain();drone.type=index?'sine':'triangle';drone.frequency.value=frequency;gain.gain.value=index?.055:.035;drone.connect(gain).connect(master);drone.start()});
 const pulse=ambience.createOscillator(),pulseDepth=ambience.createGain();pulse.frequency.value=.11;pulseDepth.gain.value=.035;pulse.connect(pulseDepth).connect(windGain.gain);pulse.start();
}
function start(){startAmbience();state.settings.name=$('#playerName').value.trim()||'UNKNOWN';state.settings.difficulty=$('#difficulty').value;state.started=Date.now();state.room=0;state.score=0;state.sanity=100;state.journal=[];loadRoom();$('#menu').classList.add('hidden');$('#game').classList.remove('hidden');requestAnimationFrame(loop)}
function loadRoom(){state.found=new Set();state.player={x:3.5,y:6.5,a:-Math.PI/2};state.started=Date.now();const r=current();$('#floorLabel').textContent=`ROOM ${String(state.room+1).padStart(2,'0')}`;$('#roomName').textContent=r.name;$('#objectiveTitle').textContent=r.objective;$('#clueList').innerHTML=r.items.map((x,i)=>`<li id="clue-${i}">□ UNKNOWN EVIDENCE</li>`).join('')+`<li id="exitClue">□ UNLOCK THE EXIT</li>`;$('#journalInvestigator').textContent=`INVESTIGATOR: ${state.settings.name}`;showMessage(`Room ${state.room+1}: ${r.name}`,2200)}
function tile(x,y){const row=current().map[Math.floor(y)];return !row||row[Math.floor(x)]!=='0'}
function move(dt){if(state.paused||$('.overlay:not(.hidden)'))return;let speed=dt*2.2,dx=0,dy=0;if(state.keys.w||state.keys.ArrowUp){dx+=Math.cos(state.player.a)*speed;dy+=Math.sin(state.player.a)*speed}if(state.keys.s||state.keys.ArrowDown){dx-=Math.cos(state.player.a)*speed;dy-=Math.sin(state.player.a)*speed}if(state.keys.a){dx+=Math.cos(state.player.a-Math.PI/2)*speed;dy+=Math.sin(state.player.a-Math.PI/2)*speed}if(state.keys.d){dx+=Math.cos(state.player.a+Math.PI/2)*speed;dy+=Math.sin(state.player.a+Math.PI/2)*speed}if(!tile(state.player.x+dx,state.player.y))state.player.x+=dx;if(!tile(state.player.x,state.player.y+dy))state.player.y+=dy;if(state.keys.ArrowLeft)state.player.a-=dt*1.8;if(state.keys.ArrowRight)state.player.a+=dt*1.8}
function render(){const W=innerWidth,H=innerHeight,r=current(),fov=Math.PI/3;const sky=ctx.createLinearGradient(0,0,0,H/2);sky.addColorStop(0,'#050806');sky.addColorStop(1,'#182019');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H/2);const floor=ctx.createLinearGradient(0,H/2,0,H);floor.addColorStop(0,'#111712');floor.addColorStop(1,'#030403');ctx.fillStyle=floor;ctx.fillRect(0,H/2,W,H/2);
 const rays=Math.min(600,Math.ceil(W/3)),col=W/rays;for(let i=0;i<rays;i++){let ang=state.player.a-fov/2+(i/rays)*fov,sin=Math.sin(ang),cos=Math.cos(ang),d=.02,hit=false;while(d<14&&!hit){d+=.025;hit=tile(state.player.x+cos*d,state.player.y+sin*d)}d*=Math.cos(ang-state.player.a);const h=Math.min(H,H/(d*.85)),fog=Math.max(0,1-d/12),shade=35+55*fog;ctx.fillStyle=`rgb(${shade*.72},${shade*.82},${shade*.7})`;ctx.fillRect(i*col,H/2-h/2,col+1,h);if(i%7===0){ctx.fillStyle=`rgba(0,0,0,${.08+d/90})`;ctx.fillRect(i*col,H/2-h/2,1,h)}}
 // evidence sprites projected into view
 [...r.items.map((x,i)=>({...x,i})),{...r.exit,i:-1,type:'door'}].forEach(o=>{const dx=o.x-state.player.x,dy=o.y-state.player.y,dist=Math.hypot(dx,dy),rel=Math.atan2(dy,dx)-state.player.a,norm=Math.atan2(Math.sin(rel),Math.cos(rel));if(Math.abs(norm)<fov*.62&&dist>.2){const sx=W/2+(norm/(fov/2))*W/2,size=Math.min(160,H/(dist*1.4)),visible=!tile(state.player.x+dx*.55,state.player.y+dy*.55);if(visible){ctx.save();ctx.shadowBlur=24;ctx.shadowColor=o.type==='door'?'#87935b':'#b6473f';ctx.fillStyle=o.type==='door'?'#20291e':'#6e2f29';ctx.globalAlpha=Math.max(.2,1-dist/13);if(o.type==='door'){ctx.fillRect(sx-size*.35,H/2-size*.75,size*.7,size*1.5);ctx.fillStyle='#aebc7a';ctx.beginPath();ctx.arc(sx+size*.22,H/2,size*.04,0,7);ctx.fill()}else{ctx.beginPath();ctx.arc(sx,H/2,size*.23,0,7);ctx.fill();ctx.fillStyle='#ddd';ctx.font=`${Math.max(9,size*.12)}px DM Mono`;ctx.textAlign='center';ctx.fillText('?',sx,H/2+4)}ctx.restore()}}});
 ctx.fillStyle='rgba(198,217,153,.025)';ctx.beginPath();ctx.moveTo(W*.47,H*.52);ctx.lineTo(W*.53,H*.52);ctx.lineTo(W*.72,H);ctx.lineTo(W*.28,H);ctx.fill()}
function nearest(){const r=current();let best=null;r.items.forEach((o,i)=>{if(state.found.has(i))return;const d=Math.hypot(o.x-state.player.x,o.y-state.player.y),a=Math.abs(Math.atan2(Math.sin(Math.atan2(o.y-state.player.y,o.x-state.player.x)-state.player.a),Math.cos(Math.atan2(o.y-state.player.y,o.x-state.player.x)-state.player.a)));if(d<1.35&&a<.75)best={kind:'item',i,o,d}});const de=Math.hypot(r.exit.x-state.player.x,r.exit.y-state.player.y);if(de<1.45)best={kind:'exit',d:de};return best}
let near=null,last=performance.now(),msgTimer;function loop(t){if($('#game').classList.contains('hidden'))return;const dt=Math.min(.05,(t-last)/1000);last=t;if(!state.paused){move(dt);state.sanity=Math.max(0,state.sanity-diff[state.settings.difficulty].drain*dt);$('#sanityBar').style.width=state.sanity+'%';$('#sanityText').textContent=Math.ceil(state.sanity);render();near=nearest();$('#prompt').classList.toggle('hidden',!near);if(near)$('#prompt span').textContent=near.kind==='exit'?'OPEN DOOR':'EXAMINE'}requestAnimationFrame(loop)}
function interact(){if(!near)return;if(near.kind==='item')openPuzzle(near.i);else if(state.found.size===current().items.length)completeRoom();else showMessage(`The door has ${current().items.length-state.found.size} locks remaining.`,1800)}
function openPuzzle(i){const p=current().items[i];state.paused=true;$('#puzzleType').textContent=`${p.type.toUpperCase()} // EVIDENCE EXAMINATION`;$('#puzzleTitle').textContent=p.title;$('#puzzleText').textContent=p.text;$('#puzzleVisual').textContent=p.visual;$('#attempts').textContent='';const root=$('#answers');root.innerHTML='';let attempts=0;p.answers.forEach((a,n)=>{const b=document.createElement('button');b.textContent=`0${n+1}  ${a}`;b.onclick=()=>{if(n===p.correct){state.found.add(i);state.score+=state.sanity<20?100:1200;state.journal.push({title:p.title,text:p.clue,room:current().name});$(`#clue-${i}`).classList.add('done');$(`#clue-${i}`).textContent=`✓ ${p.title.toUpperCase()}`;closeOverlay('puzzle');showMessage(p.clue,3000);renderJournal()}else{attempts++;state.sanity=Math.max(0,state.sanity-8);$('#attempts').textContent=`Incorrect deduction. ${Math.max(0,diff[state.settings.difficulty].mistakes-attempts)} attempt(s) before composure penalty.`;if(attempts>=diff[state.settings.difficulty].mistakes){state.score=Math.max(0,state.score-250);attempts=0}}};root.append(b)});$('#puzzle').classList.remove('hidden')}
function renderJournal(){$('#journalEntries').innerHTML=state.journal.length?state.journal.map(x=>`<article><h3>${x.title}</h3><p>${x.text}</p><small>${x.room}</small></article>`).join(''):'<p>No evidence collected. The pages wait.</p>'}
function closeOverlay(id){$('#'+id).classList.add('hidden');state.paused=false;last=performance.now()}
function completeRoom(){state.paused=true;const elapsed=Math.floor((Date.now()-state.started)/1000);state.score+=Math.max(100,1000-elapsed*3);$('#exitClue').classList.add('done');$('#exitClue').textContent='✓ EXIT UNLOCKED';$('#completeTitle').textContent=current().name;$('#completeSummary').textContent=state.room<2?'The evidence aligns, but the corridor beyond should not exist. Somewhere ahead, someone is arranging the clues for you.':'The final clue points inward. The house was never a prison—it was a confession you designed to forget.';$('#roomScore').textContent=state.score.toLocaleString();$('#roomTime').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;$('#roomComplete').classList.remove('hidden')}
function showMessage(text,ms){clearTimeout(msgTimer);$('#message').textContent=text;$('#message').classList.remove('hidden');msgTimer=setTimeout(()=>$('#message').classList.add('hidden'),ms)}
addEventListener('keydown',e=>{state.keys[e.key.toLowerCase()]=true;state.keys[e.key]=true;if(e.key.toLowerCase()==='e'&&!state.paused)interact();if(e.key.toLowerCase()==='j'){const open=!$('#journal').classList.contains('hidden');open?closeOverlay('journal'):($('#journal').classList.remove('hidden'),state.paused=true)}if(e.key==='Escape'){if(!$('#puzzle').classList.contains('hidden'))closeOverlay('puzzle');else{$('#pause').classList.remove('hidden');state.paused=true}}});addEventListener('keyup',e=>{state.keys[e.key.toLowerCase()]=false;state.keys[e.key]=false});
canvas.addEventListener('click',()=>{if(!state.paused)canvas.requestPointerLock?.()});
addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!state.paused)state.player.a+=e.movementX*.0022});
$('#beginBtn').onclick=start;$('#pauseBtn').onclick=()=>{$('#pause').classList.remove('hidden');state.paused=true};$('#resumeBtn').onclick=()=>closeOverlay('pause');$('#menuBtn').onclick=()=>{location.reload()};$('#nextRoomBtn').onclick=()=>{state.room++;$('#roomComplete').classList.add('hidden');loadRoom();state.paused=false};$$('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));
